# FROM localhost:5000/fedora:latest as BASE

# RUN dnf install -y golang

FROM localhost:5000/golang:latest as BASE 

WORKDIR /mydir

COPY web.go .

RUN CGO_ENABLED=0 go build -ldflags "-s -w" web.go

FROM scratch

COPY --from=BASE /mydir/web ./

CMD ["/web"]
