services:

  registry:

    image: docker.io/registry:latest
    container_name: registry
    restart: unless-stopped
    volumes:
      - registry_data:/var/lib/registry
    ports:
      - 5000:5000

  portainer:

    depends_on:
      - registry
    image: localhost:5000/portainer-ce:latest
    container_name: portainer
    privileged: true
    restart: unless-stopped
    volumes:
      - ${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock:Z
      - portainer_data:/data
    ports:
      - 9443:9443

volumes:
  registry_data:
    name: podman_registry_data
  portainer_data:
    name: podman_portainer_data
