---

- name: Install kubernetes
  become: yes
  block:

    - name: Add kernel modules
      community.general.modprobe:
        name: "{{ item }}"
        persistent: present
      loop:
        - overlay
        - br_netfilter

    - name: Create system configuration for kubernetes networking
      file:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        state: "touch"

    - name: Configure network for the CRI
      blockinfile:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        block: |
              net.bridge.bridge-nf-call-iptables = 1
              net.bridge.bridge-nf-call-ip6tables = 1
              net.ipv4.ip_forward = 1

    - name: Apply new settings
      command: sysctl --system

    - name: Disable swap for k8s
      shell: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Remove swap from fstab
      lineinfile: 
        dest: /etc/fstab 
        state: absent 
        regexp: "\\sswap\\s"

    # https://github.com/cri-o/cri-o/blob/main/install.md#supported-versions

    - name: Install via apt
      block:

        - name: Add keys for cri-o
          apt_key:
            url: "{{ item }}"
            state: present
          loop:
            - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ REMOTE_OS }}/Release.key
            - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ CRI_O_VERSION }}/{{ REMOTE_OS }}/Release.key

        - name: Add deb repo for cri-o
          apt_repository:
            repo: deb {{ item }}
            state: present
          loop:
            - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ REMOTE_OS }}/ /
            - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ CRI_O_VERSION }}/{{ REMOTE_OS }}/ /

        - name: Install cri-o
          apt:
            update_cache: true
            pkg: 
              - cri-o
              - cri-o-runc

        - name: Add keys for Kubernetes
          apt_key:
            url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
            state: present

        - name: Add deb repo for Kubernetes
          apt_repository:
            repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
            state: present

        - name: Install Kubernetes packages (apt)
          apt:
            update_cache: true
            pkg: 
              - kubelet
              - kubeadm
              - kubectl 

      vars:
        REMOTE_OS: "Debian_12"
        CRI_O_VERSION: "1.27"
      when: ansible_pkg_mgr == "apt"

    - name: Install via dnf
      block:

        - name: Install kubernetes packages (dnf)
          dnf:
            update_cache: true
            pkg: 
              - iproute-tc
              - cri-o
              - kubernetes-master
              - kubernetes-client
              - kubernetes-kubeadm

        - name: Update kubelet resolver
          replace:
            path: /etc/systemd/system/kubelet.service.d/kubeadm.conf
            regexp: '^Environment=\"KUBELET_EXTRA_ARGS=((?!.* --resolve-conf)[^\"]+)\"'
            replace: 'Environment="KUBELET_EXTRA_ARGS=\1 --resolv-conf=/run/systemd/resolve/resolv.conf"'

        - name: Disable firewalld
          systemd:
            name: firewalld
            enabled: false
            state: stopped

      when: ansible_pkg_mgr == "dnf"

    - name: Enable and start cri-o
      systemd:
        name: crio
        enabled: true
        state: started

    - name: Enable kubelet
      systemd:
        name: kubelet
        enabled: true

