---

- name: Download k3s
  get_url:
    url: https://get.k3s.io
    dest: ~/k3s_install
    mode: 0755

- name: Add my repostory - crictl 
  become: yes
  lineinfile: 
    name: /etc/containers/registries.conf.d/010-c2-node.conf
    create: yes
    state: present
    line: |
      [[registry]]
      location="{{ c2_node }}:5000"
      insecure=true

- name: Update resolver configuration
  become: yes
  lineinfile:
    name: /etc/systemd/resolved.conf
    state: present
    regexp: "^#MulticastDNS=no$"
    line: "MulticastDNS=yes"

- name: Restart resolver
  become: yes
  systemd_service:
    state: restarted
    name: systemd-resolved.service

- name: Ping host to verify connectivity
  ping:
    data: "{{ c2_node }}"
