---

- name: Populate service facts - before install
  service_facts:


- name: Install k3s
  when: "'k3s-agent.service' not in services or services['k3s-agent.service'].state != 'running'"
  block:

  - name: Install k3s
    become: yes
    command: ~core/k3s_install
    environment:
      K3S_KUBECONFIG_MODE: "644"
      K3S_URL: "https://{{ hostvars[groups['master'][0]].ansible_default_ipv4.address }}:6443" 
      K3S_TOKEN: "{{lookup('file', '../.kube/node_token.txt')}}"

  - name: Add my repostory - k3s
    become: yes
    lineinfile: 
      name: /etc/rancher/k3s/registries.yaml
      create: yes
      state: present
      line: |
        mirrors:
          "myreg.local":
            endpoint:
              - "http://{{ c2_ip.stdout }}:5000"

  - name: Restart k3s agent
    become: yes
    systemd_service:
      state: restarted
      name: k3s-agent.service
    when: "'k3s-agent.service' in services"

