---

- name: Populate service facts - before install
  service_facts:

- name: Install k3s
  when: "'k3s.service' not in services or services['k3s.service'].state != 'running'"
  block:

  - name: Install k3s
    become: yes
    command: ~core/k3s_install
    environment:
      K3S_KUBECONFIG_MODE: "644"
    
  - name: Add my repostory - k3s
    become: yes
    lineinfile: 
      name: /etc/rancher/k3s/registries.yaml
      create: yes
      state: present
      line: |
        mirrors:
          "myreg.local":
            endpoint:
              - "http://{{ c2_ip.stdout }}:5000"

  - name: Restart k3s control plane
    become: yes
    systemd_service:
      state: restarted
      name: k3s.service

- name: Save the node token on the host
  become: yes
  fetch:
    src: /var/lib/rancher/k3s/server/node-token
    dest: ../.kube/node_token.txt
    flat: yes

- name: Create .kube directory on remote 
  file:
    path: ~/.kube
    state: directory

- name: Copy k32s config to local directory
  copy:
    remote_src: yes
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~/.kube/config

- name: Copy k32s config to host
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ../.kube/config
    flat: yes

- name: Set cluster ip address in local config file
  delegate_to: localhost
  lineinfile:
    name: ../.kube/config
    regexp: '^(\s+server: https://).*(:6443)$'
    line: '\g<1>{{ hostvars[groups["master"][0]].ansible_default_ipv4.address }}\2'
    backrefs: yes
