FROM myreg.local/base/python:slim

RUN pip install -U pip \
                   flask \
                   mysql-connector-python; \
    pip cache purge

COPY *.py .
COPY *.sql .
COPY templates/* templates/

CMD ["python", "app.py"]