# Use root/example as user/password credentials

version: '3'

services:

  db:
    image: myreg.local/utils/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: myreg.local/utils/adminer:latest
    ports:
      - 8080:8080

  flask:
    build:
      context: app

    image: flaskapp:v1-compose
    ports:
      - 8081:8081

volumes:
  mysql_data:
    name: mysql_data
