FROM localhost:5000/python:3.11-slim

RUN pip install -U pip \
                   flask \
                   mysql-connector-python; \
    pip cache purge

COPY *.py .
COPY *.sql .
COPY templates/* templates/

CMD ["python", "app.py"]