CREATE DATABASE IF NOT EXISTS flask;

USE flask;

DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    title TEXT NOT NULL,
    content TEXT NOT NULL
);
