---

version: '3.1'

services:

  flask:

    build:
      context: app

    image: localhost:5000/flaskapp/app:v3

  init:

    build:
      context: init_db

    image: localhost:5000/flaskapp/init:v3
