# kubectl create secret generic dbauth --from-literal=password=password

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-09-19T13:08:09Z"
  labels:
    app: flask-config
  name: flask-config-pod
spec:
  containers:
  - image: lily-arm.local:5000/flaskapp:k8s-config
    name: flask-config
    command: ["python"]
    args: 
      - "app.py"
      - "--password=$(PASSWORD)"
      - "--webport=$(WEBPORT)"
      - "--dbhost=$(DBHOST)"
    env:
      - name: DBHOST
        value: "mysql-config"
      - name: WEBPORT
        value: "8085"
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: dbauth
            key: password  
    imagePullPolicy: Always
    ports:
    - containerPort: 8085
      hostPort: 8085

---

apiVersion: v1
kind: Service
metadata:
  name: flask-config
spec:
  ports:
  - port: 8085
    nodePort: 30101
  type: NodePort
  selector:
    app: flask-config
