---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-09-19T13:08:09Z"
  labels:
    app: flask
  name: flask-pod
spec:
  containers:
  - image: lily.local:5000/flaskapp:k8s-3
    name: flask-container
    command: ["python"]
    args: 
      - "app.py"
      - "--password=$(PASSWORD)"
      - "--webport=$(WEBPORT)"
      - "--dbhost=$(DBHOST)"
    env:
      - name: DBHOST
        value: "mysql-config"
      - name: WEBPORT
        value: "8080"
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: flask-secrets
            key: user-password  
    imagePullPolicy: Always
    ports:
    - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  ports:
  - port: 8085
    targetPort: 8080
    nodePort: 30101
  type: NodePort
  selector:
    app: flask
