---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql
  name: db-pod
spec:
  containers:
  - image: docker.io/mysql:latest
    name: db-container
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: example
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-vol
    ports:
    - containerPort: 3306
      name: mysql
  volumes:
  - name: mysql-vol
    persistentVolumeClaim:
      claimName: mysql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
