---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deployment
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
      name: adminer-pod
    spec:
      containers:
      - args:
        - php
        - -S
        - '[::]:8080'
        - -t
        - /var/www/html
        image: myreg.local/utils/adminer:latest
        name: adminer-container
        ports:
        - containerPort: 8080
          hostPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: adminer-service
spec:
  ports:
  - port: 8080
    nodePort: 30002
  type: NodePort
  selector:
    app: adminer
