FROM myreg.local/base/python:slim

RUN pip install -U pip \
                   flask \
                   mysql-connector-python; \
    pip cache purge

WORKDIR /opt
COPY app.py .
COPY templates/* templates/

CMD ["python", "app.py"]