---

- name: Setup ssh keys on hosts
  hosts: k8s_vagrant

  tasks:
    - name: Set authorized key 
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ecdsa.pub') }}"
