---

- hosts: k8s
  remote_user: kube
  become: yes

  vars:
    REMOTE_OS: "xUbuntu_20.04"
    CRI_O_VERSION: "1.27"

  tasks:

    - name: Add kernel modules
      modprobe:
        name: "{{ item }}"
      loop:
        - overlay
        - br_netfilter

    - name: Create system configuration for kubernetes networking
      file:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        state: "touch"

    - name: Configure network for the CRI
      blockinfile:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        block: |
              net.bridge.bridge-nf-call-iptables = 1
              net.bridge.bridge-nf-call-ip6tables = 1
              net.ipv4.ip_forward = 1

    - name: Apply new settings
      command: sysctl --system

    - name: Add keys for CRI_O
      apt_key:
        url: "{{ item }}"
        state: present
      loop:
        - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ REMOTE_OS }}/Release.key
        - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ CRI_O_VERSION }}/{{ REMOTE_OS }}/Release.key

    - name: Add deb repo for cri-o
      apt_repository:
        repo: deb {{ item }}
        state: present
      loop:
        - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ REMOTE_OS }}/ /
        - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ CRI_O_VERSION }}/{{ REMOTE_OS }}/ /

    - name: Install cri-o
      apt:
        update_cache: true
        pkg: 
          - cri-o
          - cri-o-runc

    - name: Enable and start cri-o service
      systemd:
        name: crio
        enabled: true
        state: started

    - name: Disable swap right now
      shell: |
        swapoff -a

    - name: Remove from fstab
      lineinfile: 
        dest: /etc/fstab 
        state: absent 
        regexp: "\\sswap\\s"

    - name: Add keys for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add deb repo for Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Install Kubernetes
      apt:
        update_cache: true
        pkg: 
          - kubelet
          - kubeadm
          - kubectl 

  