# Use root/example as user/password credentials
version: '3.1'

services:

  flask:

    build:
      context: app
      dockerfile: ../Containerfile 

    image: flaskapp:k8s
    ports:
      - 8082:8081
