---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-09-19T13:07:56Z"
  labels:
    app: adminer
  name: adminer-pod
spec:
  containers:
  - args:
    - php
    - -S
    - '[::]:8080'
    - -t
    - /var/www/html
    image: docker.io/adminer:latest
    name: adminer-container
    ports:
    - containerPort: 8080
      hostPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  ports:
  - port: 8080
    nodePort: 30002
  type: NodePort
  selector:
    app: adminer
