# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.4.1

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-09-19T13:07:41Z"
  labels:
    app: mysql
  name: flaskdb-pod
spec:
  containers:
  - image: docker.io/mysql:latest
    name: flask-db
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: example
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-vol
    ports:
    - containerPort: 3306
      name: mysql
  volumes:
  - name: mysql-vol
    persistentVolumeClaim:
      claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  type: NodePort
  selector:
    app: mysql
