---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: flask
  name: flask-pod
spec:
  containers:
  - image: myreg.local/flaskapp/app:v2
    name: flask-container
    command: ["python"]
    args: ["app.py", "--password=password"]
    imagePullPolicy: Always
    ports:
    - containerPort: 8081
      hostPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  ports:
  - port: 8081
    nodePort: 30001
  type: NodePort
  selector:
    app: flask
