---

- name: Setup k8s master node
  hosts: master
  tags: master
  tasks:
    - include_tasks: includes/os_setup.yaml
    - include_tasks: includes/k8s_install.yaml
    - include_tasks: includes/k8s_master.yaml

- name: Setup k8s worker nodes
  hosts: workers
  tags: workers
  tasks:
    - include_tasks: includes/os_setup.yaml
    - include_tasks: includes/k8s_install.yaml
    - include_tasks: includes/k8s_worker.yaml
