--- 

- name: List all known variables and facts
  hosts: all
  tasks:

  # - debug:
      # var: hostvars

  - name: Look up A (IPv4) records for c2_node
    command: "dig +short {{c2_node}}"
    register: c2_ip    

  - debug:
      msg: "{{c2_ip.stdout[0]}}"

  - name: Populate service facts - before install
    service_facts:

  # - debug:
  #     var: services

  - name: Service
    debug: 
      var: "'k3s-agent.service' not in services"

  - name: State
    debug: 
      var: "services['k3s-agent.service'].state != 'running'"

  - name: State Display
    debug: 
      var: "services['k3s-agent.service'].state"

  - name: Both
    debug: 
      var: "'k3s-agent.service' not in services or services['k3s-agent.service'].state != 'running'"


