---

- name: Setup k3s master node
  hosts: master
  tags: master
  tasks:
    - include_tasks: includes/k3s_preinstall.yaml
    - include_tasks: includes/k3s_master.yaml
    - include_tasks: includes/k8s_dashboard.yaml

- name: Setup k3s worker node
  hosts: workers
  tags: worker
  tasks:
    - include_tasks: includes/k3s_preinstall.yaml
    - include_tasks: includes/k3s_worker.yaml
