# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "starboard/ubuntu-arm64-20.04.5"

  config.vm.define "test1" do |test1|

    test1.vm.hostname = "test1"

    # Test 1
    # DNCP reservations are not available on this platform
    # test1.vm.provider "vmware_desktop" do |vmw|
    #   vmw.base_mac = "01:02:03:04:05:06"
    #   vmw.base_address = "192.168.11.110"
    # end
    
    # Test 2
    # Can ping fromn vm out (on base if)
    # Unable to connect to from host
    # test1.vm.network "public_network", ip: "192.168.11.100"
    
    # Test 3
    # Can ping fromn vm out (on base if)
    # Can ping/ssh other vm
    # Can ping/ssh from host
    test1.vm.network "private_network", ip: "192.168.11.100"
    
  end
  
  config.vm.define "test2" do |test2|
    
    test2.vm.hostname = "test2"

    # Test 1
    # test2.vm.provider "vmware_desktop" do |vmw|
    #   vmw.base_mac = "01:02:03:04:05:07"
    #   vmw.base_address = "192.168.11.111"
    # end
    
    # test2.vm.network "public_network", ip: "192.168.11.101"
    test2.vm.network "private_network", ip: "192.168.11.101"

  end

  config.vm.provider "vmware_desktop" do |vmw|
    vmw.gui = true
    vmw.memory = "4096"
  end
  
end
