# Use root/example as user/password credentials
version: '3.1'

services:

  flask:

    build:
      context: app
      dockerfile: ../Containerfile 

    image: localhost:5000/flaskapp:k8s-2
    ports:
      - 8082:8081
