---

- name: Add my repostory - crictl 
  become: yes
  lineinfile: 
    name: /etc/containers/registries.conf.d/010-lily.conf
    create: yes
    state: absent
    line: |
      [[registry]]
      location="lily.local:5000"
      insecure=true

- name: Add my repostory - k3s
  become: yes
  lineinfile: 
    name: /etc/rancher/k3s/registries.yaml
    create: yes
    state: absent
    line: |
      mirrors:
        "lily.local:5000":
          endpoint:
            - "http://lily.local:5000"

- name: Populate service facts
  service_facts:

- name: Restart k3s control plane
  become: yes
  systemd_service:
    state: restarted
    name: k3s.service
  when: "'k3s.service' in services"

- name: Restart k3s agent
  become: yes
  systemd_service:
    state: restarted
    name: k3s-agent.service
  when: "'k3s-agent.service' in services"