---

- name: Add my repostory - crictl 
  become: yes
  lineinfile: 
    name: /etc/containers/registries.conf.d/010-c2-node.conf
    create: yes
    state: present
    line: |
      [[registry]]
      location="{{ c2_node }}:5000"
      insecure=true

- name: Add my repostory - k3s
  become: yes
  lineinfile: 
    name: /etc/rancher/k3s/registries.yaml
    create: yes
    state: present
    line: |
      mirrors:
        "localhost.local":
          endpoint:
            - "http://{{ c2_node }}:5000"

- name: Check for config existance
  stat: path=/etc/rancher/k3s/k3s.yaml
  register: file

- name: Copy k32s config to local directory
  copy:
    remote_src: yes
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~/.kube/config
  when: file.stat.exists

- name: Populate service facts
  service_facts:

- name: Restart k3s control plane
  become: yes
  systemd_service:
    state: restarted
    name: k3s.service
  when: "'k3s.service' in services"

- name: Restart k3s agent
  become: yes
  systemd_service:
    state: restarted
    name: k3s-agent.service
  when: "'k3s-agent.service' in services"