# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "starboard/ubuntu-arm64-20.04.5"

  config.vm.define "master" do |master|

    master.vm.hostname = "k8s-master"

    # config.vm.provider "vmware_desktop" do |vmw|
    #   vmw.base_mac = "01:02:03:04:05:06"
    #   vmw.base_address = "192.168.11.101"
    # end
    
    # config.vm.network "public_network", ip: "192.168.11.101"
    # master.vm.network "private_network", ip: "192.168.11.101"

  end

  config.vm.define "worker1" do |client|

    client.vm.hostname = "k8s-worker1"
    # client.vm.network "public_network", ip: "192.168.11.102"
    # client.vm.network "private_network", ip: "192.168.11.102"

  end

  config.vm.provider "vmware_desktop" do |vmw|
    vmw.gui = true
    vmw.memory = "4096"
  end
  
end
