# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.4
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-08-25T15:06:01Z"
  labels:
    app: 1flaskcomposeadminer1
  name: 1flaskcomposeadminer1
spec:
  containers:
  - args:
    - php
    - -S
    - '[::]:8080'
    - -t
    - /var/www/html
    image: localhost:5000/adminer:latest
    name: 1flaskcomposeadminer1
    ports:
    - containerPort: 8080
      hostPort: 8080
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE

