# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.4

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-08-25T15:05:42Z"
  labels:
    app: 1flaskcomposedb1
  name: 1flaskcomposedb1
spec:
  containers:
  - args:
    - mysqld
    image: localhost:5000/mysql:latest
    name: 1flaskcomposedb1
    ports:
    - containerPort: 3306
      hostPort: 3306
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: 701a434ecd23396987e665fddfa70f53f240e55fbe17323d5ebdee595418d7f0-pvc
  volumes:
  - name: 701a434ecd23396987e665fddfa70f53f240e55fbe17323d5ebdee595418d7f0-pvc
    persistentVolumeClaim:
      claimName: 701a434ecd23396987e665fddfa70f53f240e55fbe17323d5ebdee595418d7f0

