# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.4
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-08-25T15:05:50Z"
  labels:
    app: 1flaskcomposeflask1
  name: 1flaskcomposeflask1
spec:
  containers:
  - image: localhost/flaskapp:latest
    name: 1flaskcomposeflask1
    ports:
    - containerPort: 8081
      hostPort: 8081
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE

